version: '3.5'

services:
  nginx-proxy:
    image: jwilder/nginx-proxy
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro

  whoami:
    image: jwilder/whoami
    environment:
      - VIRTUAL_HOST=whoami.local

  workspace:
    image: khhdocker/workspace:java2
    volumes:
      - "~/:/www"
    tty: true

networks:
  default:
    name: mynetwork 


